def test_fail():
    raise Exception('fail')
